module.exports = {
  env: {
		RECAPTCHA_PUBLIC: process.env.RECAPTCHA_PUBLIC,
		VERIFY_CAPTCHA_ENDPOINT: process.env.VERIFY_CAPTCHA_ENDPOINT,
		GCP_VERIFY_CAPTCHA_ENDPOINT: process.env.GCP_VERIFY_CAPTCHA_ENDPOINT,
		GCP_MAILING_ENDPOINT: process.env.GCP_MAILING_ENDPOINT,
    YOUTUBE_EMBED_ENDPOINT: process.env.YOUTUBE_EMBED_ENDPOINT,
		INSTAGRAM_EMBED_ENDPOINT: process.env.INSTAGRAM_EMBED_ENDPOINT,
		INSTAGRAM_PUBLIC: process.env.INSTAGRAM_PUBLIC,
		INSTAGRAM_SECRET: process.env.INSTAGRAM_SECRET,
  },
}
